spring:
  # 配置thymeleaf，可以用界面跳转
  thymeleaf:
    mode: HTML
    cache: false
    encoding: utf-8
  # 指定配置哪种环境
  profiles:
    active: dev
  messages:
    basename: i18n/messages

comment.avatar: /images/avatar.png

